# Generated by Django 5.2.14 on 2026-05-28 13:52

import django.db.models.deletion
import django.utils.timezone
import documents.models.document_model
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_name', models.CharField(help_text='Original filename the user uploaded.', max_length=255)),
                ('file', models.FileField(upload_to=documents.models.document_model.user_document_path)),
                ('file_type', models.CharField(blank=True, help_text='Detected type: pdf, docx, csv, etc.', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes.')),
                ('parsed_text', models.TextField(blank=True, default='', help_text='Raw text extracted by the parser.')),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('parse_error', models.TextField(blank=True, default='', help_text='Error message if parsing failed.')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='user.user')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
