# Generated by Django 5.2.14 on 2026-05-29 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['uploaded_at']},
        ),
    ]
